name: main build

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "0_7_5"
            viash_version: "0.7.5"
          - name: "0_8_6"
            viash_version: "0.8.6"
          - name: "0_9_0_RC6"
            viash_version: "0.9.0-RC6"

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/cache@v4
        with:
          path: ~/.local/bin/viash
          key: viash_${{ matrix.name }}
  
      - uses: viash-io/viash-actions/setup@v5
        if: ${{ hashFiles('~/.local/bin/viash') == '' }}
        with:
          version: ${{ matrix.viash_version }}

      - name: Remove target folder from .gitignore
        run: |
          # allow publishing the target folder
          sed -i '/^target.*/d' .gitignore

      - uses: viash-io/viash-actions/ns-build@v5
        with:
          config_mod: .functionality.version := 'build_${{ matrix.name }}'
          parallel: true

      - name: Build nextflow schemas
        uses: viash-io/viash-actions/pro/build-nextflow-schemas@v5
        with:
          workflows: src
          components: src
          viash_pro_token: ${{ secrets.GTHB_PAT }}
          tools_version: 'build_${{ matrix.name }}'
    
      - name: Build parameter files
        uses: viash-io/viash-actions/pro/build-nextflow-params@v5
        with:
          workflows: src
          components: src
          viash_pro_token: ${{ secrets.GTHB_PAT }}
          tools_version: 'build_${{ matrix.name }}'

      - name: Deploy to target branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: 'build_${{ matrix.name }}'

      - name: Build container
        uses: viash-io/viash-actions/ns-build@v5
        with:
          parallel: true
          config_mod: .functionality.version := 'build_${{ matrix.name }}'
          platform: docker
          setup: build
          
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GTHB_USER }}
          password: ${{ secrets.GTHB_PAT }}

      - name: Push container
        uses: viash-io/viash-actions/ns-build@v5
        with:
          config_mod: .functionality.version := 'build_${{ matrix.name }}'
          platform: docker
          setup: push
